#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
fill_addresses.py
=================
_notes_import_output/ 안의 노트 중 ## 위치가 TODO 플레이스홀더인 것들을
Nominatim (OpenStreetMap) → Photon (Komoot) 폴백으로 주소를 채운다.

Nominatim은 1초당 1요청 제한이 있으므로 rate-limit 준수.
결과는 _data/geocode_cache.yml 와 별개의 _data/address_cache.yml 에 저장.

사용법
  python scripts/gmaps_import/fill_addresses.py --dry-run     # 미리보기
  python scripts/gmaps_import/fill_addresses.py               # 실제 채우기
  python scripts/gmaps_import/fill_addresses.py --only "산리오"  # 일부만
  python scripts/gmaps_import/fill_addresses.py --limit 5     # 처음 5개만
"""
import argparse
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NOTES_DIR = ROOT / "_notes_import_output"
CACHE_FILE = ROOT / "_data" / "address_cache.yml"

UA = "fimplace-import/1.0 (claude.hlight@gmail.com)"
NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
PHOTON_URL = "https://photon.komoot.io/api/"


def http_get_json(url, params, timeout=10):
    q = urllib.parse.urlencode(params)
    req = urllib.request.Request(f"{url}?{q}", headers={"User-Agent": UA, "Accept-Language": "ja,ko;q=0.8"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode("utf-8"))


def geocode_nominatim(query):
    try:
        data = http_get_json(NOMINATIM_URL, {
            "q": query,
            "format": "json",
            "limit": 1,
            "accept-language": "ja,ko",
        })
        if data and isinstance(data, list):
            d = data[0]
            return {"display_name": d.get("display_name"), "lat": d.get("lat"), "lon": d.get("lon"), "src": "nominatim"}
    except Exception as e:
        print(f"  ! nominatim error: {e}", file=sys.stderr)
    return None


def geocode_photon(query):
    try:
        data = http_get_json(PHOTON_URL, {"q": query, "limit": 1, "lang": "ja"})
        feats = data.get("features") or []
        if feats:
            f = feats[0]
            p = f.get("properties", {})
            geom = f.get("geometry", {}).get("coordinates", [None, None])
            parts = [p.get(k) for k in ("name","street","housenumber","postcode","city","state","country") if p.get(k)]
            display = ", ".join(parts) if parts else p.get("name", "")
            return {"display_name": display, "lat": geom[1], "lon": geom[0], "src": "photon"}
    except Exception as e:
        print(f"  ! photon error: {e}", file=sys.stderr)
    return None


def geocode(query):
    """Nominatim 우선, 실패시 Photon."""
    r = geocode_nominatim(query)
    if r and r.get("display_name"):
        return r
    time.sleep(0.3)
    return geocode_photon(query)


# 매우 간단한 YAML 캐시 (key: value)
def load_cache():
    cache = {}
    if not CACHE_FILE.exists():
        return cache
    for line in CACHE_FILE.read_text(encoding="utf-8").splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        if ":" in line:
            k, _, v = line.partition(":")
            cache[k.strip()] = v.strip().strip('"').strip("'")
    return cache


def save_cache(cache):
    CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# auto-generated by fill_addresses.py"]
    for k in sorted(cache):
        v = cache[k].replace('"', '\\"')
        lines.append(f'"{k}": "{v}"')
    CACHE_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


TODO_PATTERN = re.compile(r"<!--\s*TODO:\s*정확한 일본어 주소[^>]*-->")


def fill_file(path, cache, dry_run=False):
    text = path.read_text(encoding="utf-8")
    if not TODO_PATTERN.search(text):
        return False, "no-todo"

    title = path.stem
    # 캐시 확인
    if title in cache and cache[title]:
        addr = cache[title]
        src = "cache"
    else:
        # 검색: 일본 가정. 제목에 일본어/한자가 있으면 그대로, 한글만이면 + " 일본"
        q1 = title
        # 한글 전용이면 " Japan" 부가
        if re.fullmatch(r"[\sA-Za-z0-9ㄱ-㆏가-힯.,\-&®()'’]+", title) and not re.search(r"[぀-ヿ一-鿿]", title):
            q1 = f"{title} Japan"
        print(f"  [geocoding] {title} ← {q1}")
        result = geocode(q1)
        if not result or not result.get("display_name"):
            return False, "no-match"
        addr = result["display_name"]
        src = result.get("src", "?")
        cache[title] = addr
        time.sleep(1.0)  # Nominatim rate limit

    new_text = TODO_PATTERN.sub(addr, text, count=1)
    if dry_run:
        print(f"  [WOULD] {title}  ({src})\n    → {addr[:100]}")
    else:
        path.write_text(new_text, encoding="utf-8")
        print(f"  [FILL ] {title}  ({src})\n    → {addr[:100]}")
    return True, "filled"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", help="제목 substring 필터")
    ap.add_argument("--limit", type=int, default=0, help="처음 N개만 처리")
    args = ap.parse_args()

    if not NOTES_DIR.exists():
        print(f"[ERR] {NOTES_DIR} 없음", file=sys.stderr); return 2

    cache = load_cache()
    files = sorted(NOTES_DIR.glob("*.md"))
    filled = 0; skipped = 0; failed = 0; processed = 0
    for f in files:
        if args.only and args.only not in f.name:
            continue
        if args.limit and processed >= args.limit:
            break
        ok, msg = fill_file(f, cache, dry_run=args.dry_run)
        if ok:
            filled += 1
            processed += 1
        elif msg == "no-todo":
            skipped += 1
        else:
            failed += 1
            processed += 1
            print(f"  [FAIL] {f.name}: {msg}")

    if not args.dry_run:
        save_cache(cache)
    print()
    print(f"채움 {filled} | 스킵(TODO없음) {skipped} | 실패 {failed}")
    if args.dry_run:
        print("dry-run — 파일 변경 없음")
    return 0


if __name__ == "__main__":
    sys.exit(main())
